# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and run docker containers
          command: |
            docker-compose build
            docker-compose up -d website

      - run:
          name: Run unit tests
          command: docker-compose run test-runner /opt/utils/tests_unit.sh

      - run:
          name: Run integration tests
          command: docker-compose run test-runner /opt/utils/tests_integration.sh

      - run:
          name: Clean docker-compose
          command: docker-compose down

  deploy:        
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless

      - run:
          name: package and deploy site-downloader to AWS
          command: cd src/escape-rooms-club/site-downloader && sls deploy            
