# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: lambci/lambda:build-python3.6

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: create deployment package
          command: |
            virtualenv lambda_env -p python
            pip install -r src/requirements.txt -t lambda_env/lib/python3.6/site-packages/
            rm -rf dist
            mkdir dist
            cp -rf lambda_env/lib/python3.6/site-packages/* dist
            cp -r src/escape_rooms_club/scraper_parser dist/.
            cd dist && zip -r ../scraper-parser.zip . && cd ..

      - run:
          name: upload deployment package to s3
          command: aws s3 cp scraper-parser.zip s3://deployment-support/scraper-parser.zip

      - run:
          name: update AWS Lambda code
          command: aws lambda update-function-code --region eu-west-1 --function-name exitgamescz-scraper-parser --s3-bucket deployment-support --s3-key scraper-parser.zip --publish

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "src/requirements.txt" }}
