# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      
      # install prerequisities
      - run:
          name: install requirements
          command: |
            sudo pip install -r src/escape-rooms-club/site-downloader/tests/requirements.txt

      # unit
      - run:
          name: Run unit tests
          command: pytest -vvvv src/escape-rooms-club/site-downloader/tests/unit/

      # integration tests      
      - setup_remote_docker
      - run:
          name: Build and run docker images
          command: |
            cd src/escape-rooms-club/docker && sudo docker-compose build
            cd src/escape-rooms-club/docker && sudo docker-compose up -d

      - run:
          name: Create s3 bucket for integration test run
          command: |
            aws --endpoint-url http://localhost:4572 s3 mb s3://scrapers-output

      - run:
          name: Run integration tests
          command: pytest -vvvv src/escape-rooms-club/site-downloader/tests/integration/

      - run:
          name: Clean docker-compose
          command: |
            cd src/escape-rooms-club/docker && sudo docker-compose down

  deploy:        
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless

      - run:
          name: package and deploy site-downloader to AWS
          command: cd src/escape-rooms-club/site-downloader && sls deploy            
