# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: library/python:3.7-alpine3.8

    working_directory: ~/repo

    steps:
      - checkout
      
      # install prerequisities
      - run:
          name: install requirements
          command: |
            pip install awscli
            pip install pytest
            pip install requests==2.21.0

      - run:
          name: install curl
          command: |
            apk --update upgrade && apk add curl

      # unit
      - run:
          name: Run unit tests
          command: pytest -vvvv src/escape-rooms-club/site-downloader/tests/unit/

      # integration tests      
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
 
      - run:
          name: Build and run docker images
          command: |
            docker-compose build
            docker-compose up -d

      - run:
          name: Create s3 bucket for integration test run
          command: |
            aws --endpoint-url http://localhost:4572 s3 mb s3://scrapers-output

      - run:
          name: Run integration tests
          command: pytest -vvvv src/escape-rooms-club/site-downloader/tests/integration/

      - run:
          name: Clean docker-compose
          command: |
            docker-compose down

  deploy:        
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless

      - run:
          name: package and deploy site-downloader to AWS
          command: cd src/escape-rooms-club/site-downloader && sls deploy            
