version: '3'
services:
  website:
    build:
      context: .
      dockerfile: ./website/Dockerfile
    ports:
      - 5000:5000
  
  localstack:
    build:
      context: .
      dockerfile: ./localstack/Dockerfile
    environment:
      - SERVICES=s3,sqs
    ports:
      - 4572:4572
