service: site-downloader

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - s3:PutObject
       - s3:Get*
       - s3:List*
      Resource: "arn:aws:s3:::scrapers-output/*"
functions:
  site-downloader:
    handler: handler.handler
