service: site-downloader

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - s3:PutObject
       - s3:Get*
       - s3:List*
      Resource: "arn:aws:s3:::prod-scrapers-sites-content/*"

functions:
  site-downloader:
    handler: handler.handler
    events:
      - schedule:
          rate: rate(24 hours)
          input:
            site_url: "https://www.exitgames.cz/Seznam-unikovych-her"
            target_bucket: "prod-scrapers-sites-content"
            target_directory: "exitgames.cz"

custom:
  pythonRequirements:
    dockerizePip: true
    
plugins:
  - serverless-python-requirements
